package no.synth.kmpzip.zip

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull

/**
 * Tests that kmp-zip can read AES-encrypted zips generated by Zip4j.
 * Zip4j uses data descriptors (flag bit 3, compressedSize=0 in local header),
 * which exercises the data descriptor resolution path.
 */
class Zip4jInteropTest {

    private val password = Zip4jTestDataGenerator.PASSWORD

    private fun readEntryContent(zis: ZipInputStream): String =
        zis.readBytes().decodeToString()

    @Test
    fun readZip4jSingleDeflated() {
        val data = Zip4jTestDataGenerator.singleDeflated()
        val zis = ZipInputStream(data, password)
        val entry = zis.nextEntry
        assertNotNull(entry)
        assertEquals("hello.txt", entry.name)
        assertEquals(ZipConstants.DEFLATED, entry.method)
        assertEquals("Hello from Zip4j!", readEntryContent(zis))
        assertNull(zis.nextEntry)
        zis.close()
    }

    @Test
    fun readZip4jMultiDeflated() {
        val data = Zip4jTestDataGenerator.multiDeflated()
        val zis = ZipInputStream(data, password)

        val entry1 = zis.nextEntry
        assertNotNull(entry1)
        assertEquals("first.txt", entry1.name)
        assertEquals("First Zip4j entry", readEntryContent(zis))

        val entry2 = zis.nextEntry
        assertNotNull(entry2)
        assertEquals("second.txt", entry2.name)
        assertEquals("Second Zip4j entry", readEntryContent(zis))

        assertNull(zis.nextEntry)
        zis.close()
    }

    @Test
    fun readZip4jMultiDeflatedSkipFirst() {
        val data = Zip4jTestDataGenerator.multiDeflated()
        val zis = ZipInputStream(data, password)

        val entry1 = zis.nextEntry
        assertNotNull(entry1)
        // Skip first entry without reading
        zis.closeEntry()

        val entry2 = zis.nextEntry
        assertNotNull(entry2)
        assertEquals("second.txt", entry2.name)
        assertEquals("Second Zip4j entry", readEntryContent(zis))

        assertNull(zis.nextEntry)
        zis.close()
    }

    @Test
    fun readZip4jSingleStored() {
        val data = Zip4jTestDataGenerator.singleStored()
        val zis = ZipInputStream(data, password)
        val entry = zis.nextEntry
        assertNotNull(entry)
        assertEquals("stored.txt", entry.name)
        assertEquals(ZipConstants.STORED, entry.method)
        assertEquals("Stored Zip4j content", readEntryContent(zis))
        assertNull(zis.nextEntry)
        zis.close()
    }

    // ---- Legacy (ZipCrypto) encryption from Zip4j ----

    @Test
    fun readZip4jLegacyDeflated() {
        val data = Zip4jTestDataGenerator.legacyDeflated()
        val zis = ZipInputStream(data, password)
        val entry = zis.nextEntry
        assertNotNull(entry)
        assertEquals("legacy.txt", entry.name)
        assertEquals(ZipConstants.DEFLATED, entry.method)
        assertEquals("Hello from Zip4j legacy!", readEntryContent(zis))
        assertNull(zis.nextEntry)
        zis.close()
    }

    @Test
    fun readZip4jLegacyMultiDeflated() {
        val data = Zip4jTestDataGenerator.legacyMultiDeflated()
        val zis = ZipInputStream(data, password)

        val entry1 = zis.nextEntry
        assertNotNull(entry1)
        assertEquals("first.txt", entry1.name)
        assertEquals("First legacy entry", readEntryContent(zis))

        val entry2 = zis.nextEntry
        assertNotNull(entry2)
        assertEquals("second.txt", entry2.name)
        assertEquals("Second legacy entry", readEntryContent(zis))

        assertNull(zis.nextEntry)
        zis.close()
    }

    @Test
    fun readZip4jLegacyStored() {
        val data = Zip4jTestDataGenerator.legacyStored()
        val zis = ZipInputStream(data, password)
        val entry = zis.nextEntry
        assertNotNull(entry)
        assertEquals("stored.txt", entry.name)
        assertEquals(ZipConstants.STORED, entry.method)
        assertEquals("Stored legacy content", readEntryContent(zis))
        assertNull(zis.nextEntry)
        zis.close()
    }
}
